version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: always
    volumes:
      - ./app:/var/www
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d